print '''
Each new term in the Fibonacci sequence is generated by adding he previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
    '''

def problem():
    F,s = [0,1],0
    while F[len(F)-1] < 4000000:
        F.append(F[len(F)-1]+F[len(F)-2])
        if F[len(F)-1]%2 == 0: s += F[len(F)-1]
    print s

problem()
